### PR TITLE
Add helix

### PR DESCRIPTION
**Pull request by ckuethe**
This diff adds support for helixes via the GH card

### CODE REVIEW

**Comment by wsnook** [comment]
@ckuethe Thanks! I haven't actually tested this since I don't have a nec2 environment set up at the moment, but reading through the code it looks cool. I'm gonna merge this under the assumption that it works, or that if it doesn't, someone will come along sooner or later to let me know.

**Comment by ckuethe** [comment]
It works; I used it to compute a collinear antenna with phase loops.

On Wed, Jul 29, 2015 at 7:07 PM, Will Snook <notifications@github.com>
wrote:

> Merged #2 <https://github.com/wsnook/nec2-toys/pull/2>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wsnook/nec2-toys/pull/2#event-369005482>.
>



-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?

**Comment by ckuethe** [comment]
Here's an example of what addHelix() makes super easy.

https://gist.github.com/ckuethe/815406b47a2acc3a5e4c

collinear

On Wed, Jul 29, 2015 at 7:34 PM, Chris Kuethe <chris.kuethe@gmail.com>
wrote:

> It works; I used it to compute a collinear antenna with phase loops.
>
> On Wed, Jul 29, 2015 at 7:07 PM, Will Snook <notifications@github.com>
> wrote:
>
>> Merged #2 <https://github.com/wsnook/nec2-toys/pull/2>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wsnook/nec2-toys/pull/2#event-369005482>.
>>
>
>
>
> --
> GDB has a 'break' feature; why doesn't it have 'fix' too?
>



-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?

**Comment by wsnook** [comment]
cool

**Pull request merged**
